apiVersion: v1
kind: Service
metadata:
  labels:
    app: argo-web
  name: argo-web
  namespace: argocd
spec:
  ports:
  - name: argo-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
  type: NodePort
