apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
data:
  password: "cGFzc3dvcmQ="
---
apiVersion: redis.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: test-redis
  namespace: redis
spec:
  forProvider:
    chargeType: "POSTPAID"
    name: "test-redis"
    TypeId: "15"
    memSize: 256
    availabilityZone: "ap-hongkong-2"
    passwordSecretRef:
      key: redis-secret
      name: password
      namespace: redis
     