apiVersion: v1
kind: Namespace
metadata:
  name: redis
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: redis
stringData:
  password: "cGFzc3dvcmQ0=_"
---
apiVersion: redis.tencentcloud.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: test-redis
  namespace: redis
spec:
  forProvider:
    chargeType: "POSTPAID"
    name: "test-redis"
    typeId: 17
    memSize: 256
    availabilityZone: "ap-hongkong-2"
    passwordSecretRef:
      key: password
      name: redis-secret
      namespace: redis
  providerConfigRef:
    name: default